### ISSUE TITLE
Proposed feature: Generate alias if none is provided

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/go-wallet#10]
Console is set up to use the key alias as a title so that users can choose to use this rather than first-last characters. Console also lists keys alphabetically by alias.

At the moment Everyone will see "Unnamed key" for each key in their wallet https://github.com/vegaprotocol/console/issues/4322

I suggest that the wallet could create an alias if the user does not specify one.

Format:
- Key 1
- Key 2
- Key 3

So if I have 1 key (called "Michael's key") and I create a new one without speciying an alias the next will be called key 2.

or If I have no keys and create one it will be called "Key 1"

i.e. "Key" + NumberOfKeys+1

I suggest hidden/tainted keys are included in the count

Yes this will lead to strange behaviour if I've changed alias and hidden some but I don't think it needs to be perfect. (although suggestions welcome).

- Key 1
- Michael's test key
- Gibbon key (tainted)
- Key 2 (I called it this)
and then I create a new key it will have the alias "Key 5"

**Comment by campbellssource** [comment]
Reopening this as it appears to not be working.

Here (v0.7): 
- the meta on the key generated on start is Null
- The meta on the 2nd key I generated: key + value are empty
<img width="573" alt="Screenshot 2021-06-15 at 13 17 01" src="https://user-images.githubusercontent.com/13255539/122050986-fe206580-cddb-11eb-810d-95e38659c394.png">

**Comment by jeremyletang** [comment]
Oh I implemented that on the command line, but not via the API actually… i’ll fix it soonish
