### ISSUE TITLE
Resync API endpointlist

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/go-wallet#107]
https://github.com/vegaprotocol/go-wallet/blob/8ff7f62bd4cc17b1decf9dd168f977b90cdbac3c/cmd/run_dump_startup.go#L22-L24

https://github.com/vegaprotocol/go-wallet/blob/8ff7f62bd4cc17b1decf9dd168f977b90cdbac3c/wallet/service.go#L166-L168

**Comment by jeremyletang** [comment]
I think it's just that the new ones are missing from the configuration not that they aren't in sync really?

**Comment by ashleyvega** [comment]
I noticed the out-of-sync is in `v0.7.0` but not in `develop`.
