### ISSUE TITLE
Proposal submission decimal place doesn't allow 0 value

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/go-wallet#114]
# Problem encountered
Proposition submission decimal place doesn't allow 0 value whereas it should.

# System response
```json
{
  "errors": {
    "proposition_submission.terms.decimal_place": ["must be positive"]
  }
}
```

**System version:** v0.39.1
**Protocol:** Specify the protocol
Proto

**Component:** Specify the components that might be related
- [Vega](https://github.com/vegaprotocol/vega/)
- [Vega Wallet](https://github.com/vegaprotocol/go-wallet/)

# Steps to reproduce

## Manual
Submit a proposal with `decimal_place` set at `0`.

# Expected behaviour
It should be allowed.

# Related problem
vegaprotocol/vega#3681

**Comment by gordsport** [comment]
Linked to https://github.com/vegaprotocol/vega/issues/3681
