### ISSUE TITLE
Improve CLI

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/go-wallet#117]
Following a discussion with @ValentinTrinque we decided to slightly change the interface of the CLI.
At the moment these are the available top level commands:
```
  genkey      Generate a new key pair for a wallet
  help        Help about any command
  import      Import a wallet using the mnemonic
  list        List keys of a wallet
  meta        Add metadata to a public key
  service     The wallet service
  sign        Sign a blob of data
  taint       Taint a public key
  verify      Verify the signature
  version     Show the version of the vega wallet
```

It's been decided to scope a couple of commands under a new `key` subgroup, here's the list of commands to be moved onto the subgroup:
```
  list        List keys of a wallet
  meta        Add metadata to a public key
  taint       Taint a public key
  generate     Generate a new key pair for a wallet
```

The 3 first one will be removed from the top level command, `generate` will be replacing genkey which also disapear from the top level.

**Comment by candida-d** [comment]
The change in commands will also impact the readme, which will need to be updated to reflect these.
