### ISSUE TITLE
Check for root-path before running any command

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/go-wallet#123]
At the moment we never check if the user have beeen initializing thhe wallet root-path before running command, which leads to this kind of not so understandable errors:
<img width="1093" alt="Screenshot 2021-07-08 at 11 56 05" src="https://user-images.githubusercontent.com/4346460/124910652-be682a80-dfe3-11eb-9825-a8e8ab19f96e.png">

I suggest that before even starting to process a command, we check if the root-path exists and if not display this kind of error message instead:
```
error: the specified root-path doesn't exist, you may want to run `vega wallet init` if you are just starting with the vega wallet.
```

**Comment by jeremyletang** [comment]
@candida-d would what do you think.

cc @ValentinTrinque

**Comment by ValentinTrinque** [comment]
Sounds a good idea

**Comment by ValentinTrinque** [comment]
We will introduce an `init` command at root level that needs to be executed before any use of the CLI and API.

Later on, we will add a specific message on each command to warn the user, however, prior work needs to be donne to handle this cleanly
