### ISSUE TITLE
Include check & warning for v1 wallet users

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/go-wallet#136]
The new wallet format means people will be required to create new keys in order to use the wallet, as the old and new formats are not compatible. The wallet should provide a warning/explanation when it detects a v1 wallet, so that users know they need to generate a new key (and what it means for their old keys).

**Comment by ashleyvega** [comment]
How difficult would it be to write a conversion function from v1 to v2 wallets? If not too difficult, this would be very friendly to wallet users, e.g.
* Testnet hosted wallet users (9826 wallets)
* self-hosted wallet users (number unknown, but 4613 downloads of `go-wallet`)
* liqbot and traderbot for Devnet, Stagnet, Testnet

**Comment by ValentinTrinque** [comment]
@ashleyvega they have a different cryptographic implementation, they cannot be mapped onto each other. Also, they are abstracted in a way both of them currently have access to the exact same commands. Except that users can't create a new v1 wallet, only a v2 wallet.

What we would like it to entirely remove the support for the v1 wallet as it's home-made and less practical, in the end.

**Comment by ValentinTrinque** [comment]
We are not going to do any work on this as it will soon disappear, in the end.

**Comment by candida-d** [comment]
@ValentinTrinque Your closing message - does that mean there's no point in warning users, or are their v1 keys still going to work?

**Comment by ValentinTrinque** [comment]
Using the legacy wallets work just as the HD wallet for every action. So everything is fine. But we plan to deprecate their support fairly soon. So I think it's a wasted effort to do anything around this legacy wallet.
