### ISSUE TITLE
Should we make the name flag a positional argument ?

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/go-wallet#144]
Since  the `name` flag is always needed, why not having it as a positional argument ?

From:

```sh
wallet key generate --name cool_name
```

To:

```sh
wallet key generate cool_name
```

Question to answer:

How do we deal with the `key meta` command that also require a pubkey ? Having several positional arguments might not be practical. Having inconsistent pattern is not practical either. The rule of thumb might be that the name is required everywhere so a positional argument make sense, but not for the rest.

**Comment by ashleyvega** [comment]
I think actions (verb, e.g. `init`) and sub-actions (noun+verb, e.g. `key generate`) should be positional, and parameters (nouns/adjectives, e.g `--name fred`, `--fast`) should not.

**Comment by ValentinTrinque** [comment]
It doesn't seem to be a good idea in the end. Closing.
