### ISSUE TITLE
[Windows] Can't run through Explorer

### ISSUE THREAD

**Issue by edd** [vegaprotocol/go-wallet#33]
<img width="493" alt="Screenshot 2020-11-20 110832" src="https://user-images.githubusercontent.com/6678/99793540-bf198280-2b20-11eb-806e-9527f9f3fd9a.png">

After #32

**Comment by candida-d** [comment]
@edd Do you think this is now covered in the existing readme set up?

**Comment by edd** [comment]
> @edd Do you think this is now covered in the existing readme set up? 

Yes
