### ISSUE TITLE
Make config file clearer

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/go-wallet#46]
In the config file that is generated by default, there are keys named `ip` that accept hostnames, not strictly IPs. These should be updated to be `host` or `url` to match the console config section:

https://github.com/vegaprotocol/go-wallet/blob/develop/wallet/config.go#L33-L52

**Comment by jeremyletang** [comment]
This was implement in: https://github.com/vegaprotocol/go-wallet/pull/49
