### ISSUE TITLE
Support sync tx submission

### ISSUE THREAD

**Issue by edd** [vegaprotocol/go-wallet#56]
In GRPC it's now possible to specify that the GRPC client should wait for a response, rather than submitting everything asynchronously. This should be exposed by `go-wallet`'s REST-ish API to allow us to catch some errors that are currently invisible

# Tasks
- Add optional `sync` property to `signTx`

**Comment by ashleyvega** [comment]
@edd Would it be useful for traderbot to be able to submit sync tx?

**Comment by jeremyletang** [comment]
> @edd Would it be useful for traderbot to be able to submit sync tx?

I might be useful for the trader bot in the case they try to place order and have no funds available. When a netwokr restart, not funds are available, but the network check if the party have any funds available of any sorts. if not, then the transaction is rejected straight in the pool. An error is return, but you will b eable to see it only with SubmitTransactionSync or SubmitTransactionCommit;

**Comment by edd** [comment]
> Also @edd this was actually already implemented.

That's great news, I totally missed that. I see it's already in the latest release - I suspect Console should switch over for some TXs.
