### ISSUE TITLE
Reset button not working

### ISSUE THREAD

**Issue by brunswyck** [vegaprotocol/go-wallet#77]
* clicking `settings` and then clicking `Full reset: Log out and delete workspaces` not working
I clicked the full reset button but the wheel just keeps on spinning and nothing happens. I left it like that for 1/2 hour. Tried multiple times after that but no luck
```bash
$ vegawallet version
vegawallet version v0.6.4 (20eee130)

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
```
Browser:
Google Chrome
Version 89.0.4389.90 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/5129017/112384682-02624880-8cef-11eb-8045-245dc7382241.png)

**Comment by brunswyck** [comment]
So how are you guys trying to delete the db? Just wondering, maybe I can pickup some javascript
```
var request = indexedDB.deleteDatabase("Vega");
request.onsuccess = function(e) { console.log("success"); };
request.onblocked = function(e) {
  console.log("blocked: " + e);
  // Close connections here
};
request.onerror = function(e) { console.log("error: " + e); };
```
you must call db.close() before delete, if you already open. otherwise you will get onblocked event
[docs](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/close)

**Comment by candida-d** [comment]
A fix for this is now live on testnet.vega.trading, and the reset button works as expected. Thanks @brunswyck for raising it!
