### ISSUE TITLE
Add BIP-39 +  SLIP-10 for recovering wallet

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/go-wallet#81]
Add the memorable words feature to recover a wallet/key, so users who forget their login details (or switch to a new computer) can regain access. 

We want to implement these two in order to provider both recoverable wallet using a mnemonic, but also hereditary deterministic key generation.

SLIP-10 is pretty much an extension of BIP-32 which enable it to work with ed25519 (https://github.com/satoshilabs/slips/blob/master/slip-0010.md)

There does not seems to be much implementation in golang, but the spec is fairly simple. It's also used by a couple of other wallet, and also hard wallet like Trezor.

This Issue will require to change the format of the wallet, we'll need to decided if we want to make them  retrocompatible too (this is a completely different / new way of generating public key), maybe having such a breaking change now, is not much of an issue until we get to mainnet.

#Acceptance

**Comment by jeremyletang** [comment]
@ValentinTrinque you may be interested with this one.

**Comment by jeremyletang** [comment]
Just for infos:
this is slip-10: https://github.com/satoshilabs/slips/blob/master/slip-0010.md
this is a go implementation of it: https://github.com/anytypeio/go-slip10 (to be looked at, run all test of the specs, etc as it's not massively tested for ed25519).
This is the lib for the bip39: https://pkg.go.dev/github.com/tyler-smith/go-bip39.
