### ISSUE TITLE
Hope to have a better way to start and connect to remind

### ISSUE THREAD

**Issue by 15226342722** [vegaprotocol/go-wallet#85]
Hope to have a better way to start and connect to remind，For example, when starting the wallet, under the windows system environment, you can click the mouse to start it quickly. You can provide a script file. When the connection is disconnected, there should be a pop-up reminder. In this way, the user experience is better. It is suggested that you can also develop quick API order operation and humanized files.

**Comment by ValentinTrinque** [comment]
We are working on improving the UX of the wallet, and we will try to cover this need. Closing it.
