### ISSUE TITLE
Add the ability to import a keypair

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/go-wallet#95]
After running `go-wallet genkey -n abc -p 123`, the public and private keys are shown:

```
new generated keys:
public: [64 hex chars]
private: [128 hex chars]
```

Add a new command, something like:
```bash
go-wallet import -n abc -p 123 --public "[64 hex chars]" --private "[128 hex chars]"
```

This is so that it is simple to transfer/import keypairs without dealing with raw wallet files.

**Comment by ValentinTrinque** [comment]
We are currently implementing support for HD wallets. The import from mnemonics will be built-in. However, this will not be implemented on the first-generation key format, as it will be deprecated on the release of HD wallets and remove not long after.

HD Wallet PR: #112
